# Generated by Django 4.0 on 2022-02-24 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choiceresponse_community_membership_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
        migrations.AddField(
            model_name='community',
            name='cool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='size',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='smelliness',
            field=models.CharField(blank=True, choices=[('Scent-Free', 'Sf'), ('Slightly Smelly', 'Ss'), ('Quite Rank', 'Qr')], max_length=20),
        ),
    ]
