# Generated by Django 4.0 on 2022-02-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_community_options_community_cool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='smelliness',
            field=models.CharField(blank=True, choices=[('1', 'Scent-Free'), ('2', 'Slightly Smelly'), ('3', 'Quite Rank')], max_length=20),
        ),
    ]
