# Generated by Django 4.0 on 2022-03-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_community_smelliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Choice'), (2, 'Text')], default=1),
            preserve_default=False,
        ),
    ]
