# Generated by Django 4.0 on 2022-05-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_post_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='bio',
            field=models.TextField(),
        ),
    ]
