# Generated by Django 4.0 on 2022-05-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0013_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.AddField(
            model_name='choiceresponse',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.profile'),
        ),
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
