# Generated by Django 4.0 on 2022-05-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_choiceresponse_user_remove_membership_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='membership',
            name='member_type',
            field=models.IntegerField(choices=[(1, 'Full'), (2, 'Social'), (3, 'Alum')], default=1),
            preserve_default=False,
        ),
    ]
